account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = '[account]'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.register, name='user_register')

]

blog/urls.py
from django.urls import path
from . import views

app_name = '[blog]'

urlpatterns = [
    path('', views.blog_title, name='blog_title'),
    path('<int:article_id>', views.blog_articles, name='blog_detail')
]

learn/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('', views.blog_title)  # 设置首页
]

account/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True, on_delete=models.DO_NOTHING)
    birth = models.DateTimeField(blank=True, null=True, verbose_name='生日')
    phone = models.CharField(max_length=11, null=True, verbose_name='手机')

    class Meta:
        verbose_name = '用户扩展信息'
        verbose_name_plural = '用户扩展信息'

    def __str__(self):
        return 'user{}'.format(self.user.username)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.


class BlogArticles(models.Model):
    title = models.CharField(max_length=300, verbose_name="标题")
    author = models.ForeignKey(User, related_name="blog_posts", on_delete=models.DO_NOTHING, verbose_name="作者")
    body = models.TextField(verbose_name="内容")
    icon = models.CharField(max_length=300, verbose_name="图片", blank=True)
    publish = models.DateTimeField(default=timezone.now, verbose_name="提交时间")

    class Meta:
        ordering = ("-publish",)
        verbose_name = "博客内容"
        verbose_name_plural = "博客内容"

    def __str__(self):
        return self.title

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField(max_length=128)
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password_two = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password_two(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password_two']:
            raise forms.ValidationError('两次输入密码不一致！')
        return cd['password_two']


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'birth')

account/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm, RegistrationForm, UserProfileForm

HTTP_METHOD_POST = 'POST'
HTTP_METHOD_GET = 'GET'


# Create your views here.
def user_login(request):
    if request.method == HTTP_METHOD_POST:
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])

            if user:
                login(request, user)
                return redirect(reverse('blog:blog_title'))
            else:
                return HttpResponse('抱歉，你的用户名或者密码错误！')
        else:
            return HttpResponse('登录成功！')

    if request.method == HTTP_METHOD_GET:
        login_form = LoginForm()
        return render(request, 'account/login.html', {'form': login_form})


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def register(request):
    if request.method == HTTP_METHOD_POST:
        user_form = RegistrationForm(request.POST)
        user_profile_form = UserProfileForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            new_profile = user_profile_form.save(commit=False)
            new_profile.user = new_user
            new_profile.save()
            return HttpResponse('注册成功！')
        else:
            return HttpResponse('注册失败！')
    else:
        user_form = RegistrationForm()
        user_profile_form = UserProfileForm()
        return render(request, 'account/register.html', {'form': user_form, 'profile': user_profile_form})

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogArticles


# Create your views here.
def blog_title(request):
    blogs = BlogArticles.objects.all()
    return render(request, 'blog/titles.html', {'blogs': blogs})


def blog_articles(request, article_id):
    article = get_object_or_404(BlogArticles, id=article_id)
    pub = article.publish
    return render(request, 'blog/content.html', {'article': article, 'publish': pub})

templates/base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
    {% include 'header.html' %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/blog/content.html
{% extends "base.html" %}
{% block title %} blog article {% endblock %}
{% block content %}
    <div class="row text-center ver", style="position: absolute; left: 50%">
        <h1>{{ article.title }}</h1>
    </div>
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <p class="text-center">
                <span>
                    {{ article.author.username }}
                </span>
                <span style="margin-left: 20px">
                    {{ publish }}
                </span>
            </p>
            <div>
                {{ article.body }}
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/titles.html
{% extends "base.html" %}
{% block title %} 博客 {% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>我的博客</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <ul>
            {% for blog in blogs %}
                <li><a href="{{ blog.id }}">{{ blog.title }}</a> </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-xs-6 col-md-4">
        <h2>广告</h2>
        <p>跟爸爸一起走吧</p>
        <img src="http://i1.umei.cc/uploads/tu/201902/9999/2cccefcc67.jpg", width="200px">
    </div>
</div>
{% endblock %}

templates/footer.html
{% load staticfiles %}
<div class="container">
    <hr>
    <p class="text-center">copy right™️</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="">
                <img src="{% static 'images/logo.png' %}" width="100px">
            </a>
        </div>
        <div>
            <ul class="nav justify-content-end">
                <li class="nav-item"><a class="nav-link active" href="{% url 'blog:blog_title' %}">博客</a> </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                           aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
                        <div class="dropdown-menu">
                          <a class="dropdown-item" href="#">设置</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="{% url 'account:user_logout' %}">登出</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link active" href="{% url 'account:user_login' %}">登录</a> </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>